### ISSUE TITLE
setup Root Systems  blog on Medium

### ISSUE THREAD

**Issue by ahdinosaur** [root-systems/cobuy#136]

**Comment by sarah-arrrgh** [comment]
TODO:

- [x] setup RS blog on medium
- [x] follow relevant people on Medium
- [x] add link to blog in RS handbook

https://medium.com/@rootsystems

**Comment by sarah-arrrgh** [comment]
PR for adding link to blog in RS handbook:
https://github.com/root-systems/handbook/pull/103

**Comment by danalexilewis** [comment]
@sarah-arrrgh I have merged this. I am not sure why it wasn't. A change may be to tag someone in as an assigned reviewer.

**Comment by michael-smith-nz** [comment]
I see we've created a new medium user rather than a publication, any reason for this?
I personally think creating a publication would be the best option as it would get the most reach. Individuals can publish stories under their own names and reach their personal followers and also publish it to the RS publication and reach RS followers.
The only downside would be that currently you cannot publish to two publications, so we couldnt publish to [Enspiral Tales](https://medium.com/enspiral-tales) as well as RS
