### ISSUE TITLE
email invite group members

### ISSUE THREAD

**Issue by ahdinosaur** [root-systems/cobuy#161]
depends on https://github.com/root-systems/cobuy/issues/159

email has basic content to say "hey, thanks for being a human on Cobuy!" with a token to create an account / login with existing account to be added to the group.

**Comment by sarah-arrrgh** [comment]
blocked by #159 and #41

**Comment by iainkirkpatrick** [comment]
nb. looks like invited group 'create your profile' tasks are getting assigned to the admin atm, need to fix.

**Comment by iainkirkpatrick** [comment]
todo:

- create a link for the invited user to visit, that contains their JWT - in the url?
- page for invitees to visit and update their password
  - do we want to lock this page from being visited by other users somehow?
- credentials patch that passes the JWT as well?

**Comment by iainkirkpatrick** [comment]
nb. currently sending an invite email even if you are the admin signing up, need to not do this for them.

**Comment by iainkirkpatrick** [comment]
chatted with mikey, he revealed how `tokenConsume` is supposed to be used, i.e. call that service to consume tokens. the schema file shows what properties can be passed in to a `.create` service call.
also instead of throwing the JWT through to the server somehow, we need to verify it and extract the tokenId - this is what tokenConsume needs.
tokenConsume will return the result of the patch operation, at which point we can call the `signIn` action with that result and the entered password. Mikey points out this logic should really be in an epic, we can do that later.
