### ISSUE TITLE
Design UI for modifying item quantities in realtime

### ISSUE THREAD

**Issue by mischa-s** [root-systems/cobuy#20]
It is currently possible to modify item quantities but the UI is not completely intuitive (i.e. it takes a bit of head scratching to understand what is happening)

Needs:
-whiteboarding of showing complicated problems in a simple and intuitive way

-implementation of tweaked design

**Comment by ahdinosaur** [comment]
what user interface we have so far:

![snapshot140](https://cloud.githubusercontent.com/assets/719605/24175068/14985940-0ef9-11e7-8667-0bf19c651e37.png)

what data we have to work with, per "order item": https://github.com/enspiral-root-systems/cobuy/blob/master/ordering/get/itemsByOrder.js#L48-L60

- batch size for supplier
- sum of all minimum intent values
- sum of all maximum intent values
- total batches met by minimums
- total remainder from minimums
- total diff between maxs and mins
- whether or not diff plus remainder is enough to fill extra batch
- total batches filled (all batches met by mins plus maybe one from extra by maxs)
- amount of minimum towards next batch (if not met)
- amount of max diff towards next batch (if not met)
- amount left in order to meet next batch

**Comment by ahdinosaur** [comment]
prior art:

- [Food Soft](https://vimeo.com/145927538)

**Comment by ahdinosaur** [comment]
> everyone gets what they want, plus some people get a bit extra to fill batches

what to communicate:

- each individuals' min (how much they want), extra (how much they are willing to receive), and expected (how much they should expect to receive based on group's activity)
- whether the group wants more than the batches met and so needs more extra
- health: green (everyone gets what they want, maybe a little extra), yellow (some people get a lot of extra), red (some people aren't getting what they want)
- who wants what, who is getting what extra, who is not getting what they want

**Comment by danalexilewis** [comment]
excited to iterate this going forward. nice short summary of the different coms the user may want.

**Comment by ahdinosaur** [comment]
superseded by https://github.com/root-systems/cobuy/issues/49
