### ISSUE TITLE
upgrade task steps flow into ordered sub-tasks, update task worker to support

### ISSUE THREAD

**Issue by iainkirkpatrick** [root-systems/cobuy#236]
and possibly remove the done button - seems bad to be able to click 'done' before you are finished with the form

**Comment by ahdinosaur** [comment]
keen for this, but also want to understand your approach because from my perspective it seems non-trivial to do "better", hence the current mvp approach.

**Comment by ahdinosaur** [comment]
as i see it, the "better" way is for these task steps to be handled as ordered sub-tasks and run through the task worker. at the moment, they are handled as single tasks, where it just so happens that each task has multiple steps.

at the moment, we only support un-ordered sub-tasks. we'd need some way to express ordered sub-tasks. then with this information, we could update the task worker component to use steppers when given ordered sub-tasks. since the task worker component is already the part that provides the "done" button, it should be easy to make more intelligent "next" buttons as described in the original post.

**Comment by gregorykan** [comment]
from first feedback session:

- any time it says "and" in a task, why is a single task and not two tasks?

**Comment by gregorykan** [comment]
broken into #434 #435 #436
