### ISSUE TITLE
create walkthrough video

### ISSUE THREAD

**Issue by ahdinosaur** [root-systems/cobuy#278]
can continue from #207. we'll need this for an upcoming demo.

**Comment by Julietbc** [comment]
@agentlewis can you confirm when specifically you need this by?

**Comment by iainkirkpatrick** [comment]
Just had a chat with @agentlewis on this - key points:

- speed up parts where the user is clicking, setting up order config, anything like that etc... takes too long when presenting
- slow down on the order summary screen, need time to talk about what's happened
- in terms of the ACTION of the video, rather than having multiple windows representing users going into the single product views and ordering, just have a single window (i.e. an admin user) looking at others ordering in the product list view and display the numbers ordered for each product. Idea being we should see numbers going up, maybe some animation etc, basically make it look exciting and like everyone is going hell-for-leather ordering things!

we aren't sure when this is needed by... hopefully not in November, but this is basically ASAP cause it's unknown.

**Comment by iainkirkpatrick** [comment]
this was done last week. 😅
