### ISSUE TITLE
bug: don't need to set up group / supplier if already part of one

### ISSUE THREAD

**Issue by iainkirkpatrick** [root-systems/cobuy#290]
currently, if the logged in user is already part of a group and the group has a supplier, when starting an order the user is still prompted to create a group / supplier as part of the pre-reqs. 

These prompts should be removed if the user is already part of at least 1 group, and / or if that group already has at least 1 supplier.

**Comment by michael-smith-nz** [comment]
With this change, we'll need to think about how someone can create a group when one already exists. Where would that function exist? Related to #158

**Comment by michael-smith-nz** [comment]
Hmmm, a few things unexpected happening here:

- the `hasNotCompletedGroupOrSupplierProfile` function on `orders.js` is using `sourceId` to find admin agents, but should be using `targetId`
- 2 new group agents are being created along with a bunch of relationships, etc. every time the 'Start Order' button is pressed

**Comment by iainkirkpatrick** [comment]
the 2 group agents being created each time Start Order is clicked is to have a group and a supplier to populate as part of the pre-reqs. IMO this should only happen if the user isn't already part of a group, and if any of their groups don't have a supplier - i.e. only create these agents if the user needs to do that part of the pre-reqs

**Comment by michael-smith-nz** [comment]
Is there any point having a 'Pre-Requisites' task? 
At the moment we have a complicated process of creating an empty agent and profile of a supplier and group and then updating them later down the pipeline. We've got a bunch of hooks in place to check if a group or supplier does not meet different criteria because of this. I suggest we move creation of groups and suppliers to the 'start order' task (mockup to come) and possibly somewhere else if users wanted to create groups and suppliers outside of starting an order.

**Comment by michael-smith-nz** [comment]
Thanks to @iainkirkpatrick I've found Mikey working on #300. Looks like this will fix this issue as there will be no Pre-Requisites task.

**Comment by michael-smith-nz** [comment]
Not relevant anymore
