### ISSUE TITLE
orders page: hovering over consumer/supplier/admin avatars should show what type of agent

### ISSUE THREAD

**Issue by gregorykan** [root-systems/cobuy#363]

**Comment by ahdinosaur** [comment]
on orders page, we should add hover so when you hover the avatar, you see what type of agent this is (consumer, supplier, admin).

**Comment by michael-smith-nz** [comment]
This must be replacing the current permanent labels?

**Comment by ahdinosaur** [comment]
@NotThatSmith i think the permanent labels are on the order page, not the orders page. this would be to make the orders page, which is more compact, have the same context on hover.

**Comment by ahdinosaur** [comment]
looking at [Avatar source code](https://github.com/mui-org/material-ui/blob/v1-beta/src/Avatar/Avatar.js), i wonder if we can pass in [img title text](https://stackoverflow.com/questions/872389/html-img-tag-title-attribute-vs-alt-attribute#872407) as a hover tooltip. otherwise, since i don't think we can re-use the tooltip functionality from IconButton, will probably will need to use `onMouseEnter` and `onMouseLeave` as described [here](https://stackoverflow.com/a/36300576) to pop open a relatively positioned box.
