### ISSUE TITLE
Update ui of Product list/grid to show how much the user has ordered

### ISSUE THREAD

**Issue by danalexilewis** [root-systems/cobuy#435]
currently there is no way to know what you have commited to a product

**Comment by ahdinosaur** [comment]
this is tricky because we only know the current amount you will receive based on the algorithm, and showing all your intents is too much information to fit inside the compact view (assuming many price specs). i'd worry that if we show the current amount based on the algorithm, it could be misleading, unless we clearly qualified it. or maybe we show a range between the price points, like `2-5`? in general i think we want to provide a useful high-level view on the products page, but expect all the detail to be in the product page.

**Comment by danalexilewis** [comment]
Yeah I here that. 

Your idea of a quick read form is interesting eg (2-4-0) we could even make the numbers hoverable so people will get a pop up explanation.

I think showing how much you are currently going to get would be a good starting place - ie if it closed right now. 

Then we can use language like “your expected” and a hover icon to explain it.

The problem with not showing anything is people have no idea what they have put commits in.

Thoughts?
